server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tool-service
          uri: lb://tool-service
          predicates:
            # CAMBIO 1: Coincidir con el frontend (/tool-service)
            - Path=/tool-service/** filters:
            # CAMBIO 2: Quitar "/tool-service" antes de pasar la petición al backend
            # Así llega limpia como "/api/v1/tools" al controlador
            - StripPrefix=1
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**
        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true