server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # --- RUTA TOOL-SERVICE ---
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool-service/**
            
        # --- RUTA CLIENT-SERVICE ---
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**

        # --- OTROS SERVICIOS ---
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan-service/**

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex-service/**

        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine-service/**
            
      globalcors:
        corsConfigurations:
          "[/**]":
            # --- CORRECCIÓN CORS ---
            allowedOriginPatterns:  # Usamos Patterns en lugar de Origins
              - "*"                 # Permite localhost, 127.0.0.1, y cualquier puerto
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:         # Permitimos todas las cabeceras para evitar bloqueos extra
              - "*"
            allowCredentials: true