server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # CORRECCIÓN 1: Usar el nombre del servicio de K8s, NO localhost
      defaultZone: http://eureka-service:8761/eureka
  instance:
    # CORRECCIÓN 2: Usar hostname predeterminado para evitar conflictos de IP
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # --- TUS RUTAS (Las mantengo igual) ---
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool-service/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan-service/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex-service/**
        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine-service/**
            
      globalcors:
        corsConfigurations:
          "[/**]":
            # CORRECCIÓN 3: Permitir TODOS los orígenes (Soluciona tu error de CORS)
            allowedOriginPatterns: 
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true