server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true # Recomendado para Kubernetes

spring:
  cloud:
    gateway:
      # --- CORRECCIÓN CRÍTICA PARA EL 403 ---
      globalcors:
        add-to-simple-url-handler-mapping: true # Permite que OPTIONS pase al manejador de CORS
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      
      discovery:
        locator:
          enabled: true

      routes:
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool-service/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan-service/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex-service/**
        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine-service/**