server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # --- RUTA TOOL-SERVICE ---
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool-service/**
          filters:                 # <--- "filters" va aquí, a la altura de "predicates"
            - StripPrefix=1        # <--- Y esto es un elemento de la lista de filtros
            
        # --- RUTA CLIENT-SERVICE ---
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/** # Sugerencia: Usa prefijos consistentes
          filters:
            - StripPrefix=1
            
        # --- OTROS SERVICIOS ---
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
          filters:
            - StripPrefix=1

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**
          filters:
            - StripPrefix=1

        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine/**
          filters:
            - StripPrefix=1
            
      # --- CORS GLOBAL ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true