server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      # --- CONFIGURACIÓN DE CORS ---
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
              # AGREGADO: Rangos de IPs locales para que funcione con Hyper-V y VirtualBox
              - "http://192.168.*"
              - "http://172.*"
              - "http://10.*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      
      discovery:
        locator:
          enabled: true # Esto permite acceder también por /NOMBRE-SERVICIO/

      # --- RUTAS MANUALES ---
      # Se recomienda usar StripPrefix=1 para que el microservicio reciba la ruta limpia
      routes:
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/tool-service/**
          filters:
            - StripPrefix=1  # Convierte /tool-service/api/... en /api/...
            
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan-service/**
          filters:
            - StripPrefix=1

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex-service/**
          filters:
            - StripPrefix=1

        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/fine-service/**
          filters:
            - StripPrefix=1