server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      # --- CONFIGURACIÓN DE CORS ---
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:*"
              - "http://localhost:*"
              - "http://192.168.*"
              - "http://172.*"
              - "http://10.*"
              # Agregamos específicamente la IP de tu Minikube para evitar bloqueos
              - "http://172.26.26.203:30000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - TokenRelay # <--- AGREGADO: Esto propaga el token JWT a todos los servicios
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false # <--- CAMBIADO: Para que respete las mayúsculas de Eureka

      # --- RUTAS MANUALES EN MAYÚSCULAS ---
      routes:
        - id: tool-service
          uri: lb://tool-service
          predicates:
            - Path=/TOOL-SERVICE/**
          filters:
            - StripPrefix=1
            
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/CLIENT-SERVICE/**
          filters:
            - StripPrefix=1

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/LOAN-SERVICE/**
          filters:
            - StripPrefix=1

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/KARDEX-SERVICE/**
          filters:
            - StripPrefix=1

        - id: fine-service
          uri: lb://fine-service
          predicates:
            - Path=/FINE-SERVICE/**
          filters:
            - StripPrefix=1