apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: ClusterIP
  selector:
    app: client-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: danielv28/client-service:latest 
        env:
        #Eureka
        - name: SERVER_PORT
          value: "8080"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "client-service"
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "client-service"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
        # Base de Datos
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db-service:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        # Keycloak
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: "http://host.minikube.internal:9090/realms/toolrent-realm"

        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
          value: "DEBUG"         