apiVersion: v1
kind: Service
metadata:
  name: kardex-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kardex-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kardex-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kardex-service
  template:
    metadata:
      labels:
        app: kardex-service
    spec:
      containers:
      - name: kardex-service
        image: danielv28/kardex-service:latest # <--- CAMBIA ESTO
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888/"
        - name: SPRING_APPLICATION_NAME
          value: "kardex-service"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: "http://keycloak-service:8080/realms/toolrent-realm"
        
        # Base de Datos
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5432/kardex_db"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password