apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
type: Opaque
data:
  # --- INSTRUCCIONES PARA OBTENER ESTOS VALORES ---
  # 1. Ve a tu Keycloak > Clients > (Tu cliente gateway) > Credentials.
  # 2. Copia el Client ID y el Client Secret.
  # 3. En tu terminal de Windows (PowerShell), convierte los valores a Base64 así:
  #    [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("tu-valor-aqui"))
  # 4. Pega el resultado abajo.
  
  # Ejemplo: si tu cliente es "gateway-client", pon el base64 aquí:
  client-id: dG9vbHJlbnQtYmFja2VuZA==
  
  # Ejemplo: pega aquí el base64 de tu Client Secret de Keycloak:
  client-secret: OElZcGdWa0g3NlRSYUM0RThoRW1uR0Y0cjd3TDNYZ0w=