apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: danielv28/report-service:latest  
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"
            
            # Nombre de la aplicación
            - name: SPRING_APPLICATION_NAME
              value: "report-service"
            
            # Eureka configuration
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "report-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            
            # Database
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db-service:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # Conexión con otros microservicios
            - name: SERVICES_LOAN_BASE_URL
              value: "http://loan-service:8080"
              
            # Seguridad Keycloak
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://10.0.134.50:9090/realms/toolrent-realm"